apiVersion: v1
kind: Service
metadata:
  labels:
    app: experiment-controller
  name: experiment-controller
spec:
  clusterIP: None
  ports:
  - port: 6666
  selector:
    app: experiment-controller

